# Generated by Django 3.2.7 on 2021-09-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dress_id',
            field=models.IntegerField(choices=[(1, 'Short ginger'), (2, 'Short brunete')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes_id',
            field=models.IntegerField(choices=[(1, 'Short ginger'), (2, 'Short brunete')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_id',
            field=models.IntegerField(choices=[(1, 'Short ginger'), (2, 'Short brunete')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_id',
            field=models.IntegerField(choices=[(1, 'Short ginger'), (2, 'Short brunete')]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_url', models.CharField(blank=True, max_length=30)),
                ('side1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='side1', to='game.game')),
                ('side2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='side2', to='game.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
