# Generated by Django 3.2.7 on 2021-09-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210906_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='invitation',
        ),
        migrations.AddField(
            model_name='profile',
            name='invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.invitation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wedding_url',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
