# Generated by Django 3.2.7 on 2021-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210906_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wedding_url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
