# Generated by Django 3.2.7 on 2021-09-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_profile_wedding_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='incorret_answers',
            new_name='incorrect_answers',
        ),
    ]
