# Generated by Django 3.2.7 on 2021-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_incorret_answers_question_incorrect_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dress_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin_id',
            field=models.IntegerField(),
        ),
    ]
