# Generated by Django 3.2.7 on 2021-09-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210908_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='questions',
            field=models.ManyToManyField(blank=True, to='game.Question'),
        ),
        migrations.AlterField(
            model_name='game',
            name='scores',
            field=models.ManyToManyField(blank=True, to='game.Score'),
        ),
    ]
